### ISSUE TITLE
AmfObject deserialize problem

### ISSUE THREAD

**Issue by richieyan** [Ventero/amf-cpp#7]
attributes in AmfObjectTraits should be a vector.
The order of the atrributes is sensitive.

**Comment by Ventero** [comment]
Thanks for your interest in amf-cpp. It's not quite clear to me why the order of attributes would matter, though. As far as I can tell, the [amf specification](http://wwwimages.adobe.com/www.adobe.com/content/dam/Adobe/en/devnet/amf/pdf/amf-file-format-spec.pdf) only requires the attribute names to be in the same order as the attribute values - which if I'm not mistaken is properly taken care of by the current implementation.

Could you please elaborate why you think this should be changed?

**Comment by richieyan** [comment]
For example, I convert a java object to an amfobject and save it as an binary data, then I use the amf-cpp to deserialize the amfobject to AmfObject.
If the attribute not in an order, the deserialise would be failed. 
Because the amfobject data in binary is write by props(in an order)...values(order by the props).

**Comment by Ventero** [comment]
Huh, you're absolutely right - can't believe I missed that.

However, there is one additional edge case to consider: what if there are duplicate property names in the list of sealed attributes? Technically, they should then still be followed by two values - even when the object contains a trait reference. This means we would actually have to store the un-deduplicated list of attribute names on the traits, and only remove duplicates when actually serializing it.

I'll think a bit more about this - but thanks a lot for pointing out this mistake!

**Comment by Ventero** [comment]
I've cherry picked your two commits from #9 and added some tests plus added some changes to (hopefully properly) deal with duplicate attribute names in ae5cd7180d0a341fb319b40fa269f8600ae9836d - so I think this can be closed.

Thank you for your contribution!

**Comment by richieyan** [comment]
Great Job!
